spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sqltest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.example.demo.entity
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*.xml
  thymeleaf:
    cache: false